### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#31]
Media upload is something vital to Twitter clients nowadays, so of course it needs to be added to Surfbird at some point.

**Roadmap:**
- [x] Media selection
- [x] Media previews in client
- [x] Passing media to backend (file paths)
- [x] Reading media and turning it into data (encode with base64)
- [x] Upload media
- [x] Attach returned media IDs to tweet and post that

**Comment by pixeldesu** [comment]
Everything is working as intended, but when I send a follow up tweet with media it tells me that the second tweet is missing the `status` parameter, which it isn't. After the error message it immediately sends the tweet nonetheless.

So, before making another release with this, I'd like to find out what's causing the error specifically.
