### ISSUE TITLE
Replies

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#32]
With commit 5399e1c663c2510b39bcef0ba0e50b8d3948f1bd there is now a tweet storage available that keeps all tweets, while the actual iterables only contain ID references to them.

With this, we can properly implement replies now.

**Roadmap:**
- [x] set `vm.$data.reply` to the tweet object from `tweetStorage`
- [x] design and implement reply display in compose view
- [x] implement proper mention/user support for textbox

**Comment by pixeldesu** [comment]
Implemented in f797a88
