### ISSUE TITLE
Alerts/Toasts for Events

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#34]
Currently there are no real replies on whether an action has been performed successfully or not.

Implement a toaster-library (maybe Toastr.js or something).

**Roadmap:**
- [ ] Find suitable library for toasts
- [ ] Implement hook(s) for event callbacks
- [ ] Implement toasts for events

**Tip:** Use status codes for return values and then set up locales for the corresponding status code, you can then easily get the specific key from the locale file.
