### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#35]
Implement a basic search for users/tweets.

**Roadmap:**
- [ ] Backend calls for Search API (`search/tweets`, `users/search`)
- [ ] Frontend call to backend + receival of data
- [ ] Frontend design + functions to clear searches
