### ISSUE TITLE
Mutes

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#36]
Because there always is some kind of content that we don't want to see.

**Types of Mutes:**
- [x] Text ("text fragment", "#hashtag")
- [x] User ("@username")
- [x] Source ("web", "Surfbird")

**Roadmap:**
- [x] Fetch initial set of user mutes from Twitter
- [ ] Set user mutes and send them to Twitter
- [x] Write custom filter to apply above mutes on all timeline types
- [x] Add modal/dialogue/tab to set mutes
- [x] As a plus, regex support for Text type mutes
