### ISSUE TITLE
Hiding Tweets

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#38]
Hide tweets and follow up content (quotes, retweets and replies), suggested by @stawberri

Due to API limitations (and trying to be sparse with our request limit) we could only hide direct descendant replies to a tweet, as all other methods would require us to fully cycle through all replied statuses, which wastes a ton of requests.

**Roadmap:**
- [x] Add action to hide tweets
- [x] Hide tweets, quotes and replies if they contain the ID of a hidden tweet
- [x] List all hidden tweets in a modal/tab/dialogue and allow to un-hide them there

**Comment by pixeldesu** [comment]
Added in cb82280
