### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#42]
Because you can't really view those yet.

**Roadmap:**
- [x] Save and update user status into object. (e.g. `app.userStorage`)
- [ ] Turn links to users into actions for Vue.js
- [ ] Add modal for profiles
- [ ] Design profile modals in reference to #21 
- [ ] Invoke on modal events to clear active (selected) user
- [ ] Add user interactions (Following, Blocking, etc.)
